// client.spec.js — the browser proof: a REAL Chromium applies the REAL
// patch ops the beam-lisp differ produced, and the DOM ends correct.
//
// This closes the one gap the headless .bl tests cannot: does a browser
// actually apply these patches to a live DOM? The fixture (fixture.json) is
// generated by test/browser/gen_fixture.bl from priv/live/diff.bl — the same
// differ the server uses — so the JS client is proven against the real wire,
// not hand-written ops.
//
// Run:  cd test/browser && npx playwright test
// (fixture.json must be regenerated first:
//    mix beam_lisp.run --path priv test/browser/gen_fixture.bl > fixture.json)

const { test, expect } = require("@playwright/test");
const fs = require("fs");
const path = require("path");

const clientJs = fs.readFileSync(
  path.join(__dirname, "../../priv/live/client.js"),
  "utf8"
);
const fixture = JSON.parse(
  fs.readFileSync(path.join(__dirname, "fixture.json"), "utf8")
);

// normalize whitespace-free HTML comparison (attribute order can vary once
// the DOM round-trips, so compare structure via a canonical serialization)
function canonical(html) {
  return html.replace(/\s+/g, " ").trim();
}

test("the JS client applies the differ's real ops in a real browser", async ({
  page,
}) => {
  // a bare page with the client loaded and a mount root
  await page.setContent('<div id="live-root"></div>');
  await page.addScriptTag({ content: clientJs });

  // MOUNT: set the root's HTML to the fixture's first paint
  await page.evaluate((mount) => {
    document.getElementById("live-root").innerHTML = mount;
  }, fixture.mount);

  // the mount shows the first row
  await expect(page.locator("#live-root li")).toHaveCount(1);
  await expect(page.locator("#live-root li").first()).toHaveText("First");

  // apply each patch step and assert the DOM matches the server's HTML for it
  for (let i = 0; i < fixture.patches.length; i++) {
    const step = fixture.patches[i];
    await page.evaluate((ops) => {
      const root = document.getElementById("live-root");
      for (const op of ops) window.Live.applyOp(root, op);
    }, step.ops);

    // the DOM's innerHTML must equal the server's rendered HTML for this step
    const got = await page.evaluate(
      () => document.getElementById("live-root").innerHTML
    );
    // the server HTML is the <ul>…</ul> outer; the root holds its children
    const wantInner = step.html.replace(/^<ul>/, "").replace(/<\/ul>$/, "");
    // the client applied ops to the <ul> which IS the root's child; compare
    // the root's rendered structure to the server's
    expect(canonical(got)).toBe(canonical(step.html));
  }
});

test("patches land correctly under parents that mix text + element children", async ({
  page,
}) => {
  // REGRESSION: the live-nav "URL changes but the page does not fully update"
  // bug. The server differ indexes a node's children as the flat text+element
  // list (diff.bl children-of), and hiccup->html joins siblings with "" so the
  // DOM childNodes mirror it. A client that walked ELEMENT-only children
  // skipped the text siblings, so a path under a node like `[:button (icon)
  // "Label"]` resolved to the wrong node (or off the end) and the op was
  // silently dropped. This replays a session of such parents and asserts the
  // DOM equals the server's HTML at every step — it fails if the client ever
  // regresses to element-only indexing.
  const mixed = fixture.mixed;
  await page.setContent('<div id="live-root"></div>');
  await page.addScriptTag({ content: clientJs });

  await page.evaluate((mount) => {
    document.getElementById("live-root").innerHTML = mount;
  }, mixed.mount);

  for (let i = 0; i < mixed.patches.length; i++) {
    const step = mixed.patches[i];
    await page.evaluate((ops) => {
      const root = document.getElementById("live-root");
      for (const op of ops) window.Live.applyOp(root, op);
    }, step.ops);
    const got = await page.evaluate(
      () => document.getElementById("live-root").innerHTML
    );
    expect(canonical(got), `mixed step ${i + 1}`).toBe(canonical(step.html));
  }
});

test("keyed reorder preserves the SAME DOM nodes (not a rewrite)", async ({
  page,
}) => {
  await page.setContent('<div id="live-root"></div>');
  await page.addScriptTag({ content: clientJs });

  // mount two keyed rows
  await page.evaluate(() => {
    document.getElementById("live-root").innerHTML =
      '<ul><li data-key="a">A</li><li data-key="b">B</li></ul>';
  });

  // tag the "a" node with a unique marker so we can prove it SURVIVES a move
  await page.evaluate(() => {
    document
      .querySelector('#live-root li[data-key="a"]')
      .setAttribute("data-survived", "yes");
  });

  // apply a move op: put "b" at index 0 (reordering a and b). The path is
  // relative to the view root element (the <ul>), so [] names the <ul>.
  await page.evaluate(() => {
    const root = document.getElementById("live-root");
    window.Live.applyOp(root, ["move", [], "b", 0]);
  });

  // order is now b, a
  const order = await page.evaluate(() =>
    Array.from(document.querySelectorAll("#live-root li")).map((el) =>
      el.getAttribute("data-key")
    )
  );
  expect(order).toEqual(["b", "a"]);

  // and the "a" node is the SAME node — its marker survived, proving a move
  // moved the node rather than rewriting it (what a string diff cannot do)
  const survived = await page.evaluate(() =>
    document
      .querySelector('#live-root li[data-key="a"]')
      .getAttribute("data-survived")
  );
  expect(survived).toBe("yes");
});
