#+TITLE: Session 154eb3356fa3516d Todos
#+DATE: 2026-08-07
#+TODO: ITEM DOING BLOCKED | DONE

* impl

** DONE Add Volatile+Reduced structs and fns to refs.ex
:PROPERTIES:
:TASK_ID: task-1
:STATUS: completed
:END:

Add BeamLisp.Volatile (process-dict box) + BeamLisp.Reduced structs, volatile/vreset!/vswap!/volatile? fns, deref clauses for both, in lib/beam_lisp/refs.ex

** DONE Extend cpp shim + core prims in rt.ex
:PROPERTIES:
:TASK_ID: task-2
:STATUS: completed
:END:

Add RT fns reduced/reduced?/reduce/peek/pop/promoting_inc/is_integer/is_ratio/is_big_decimal/is_sorted/is_nan/is_list/volatile/vreset/vswap; register cpp_prims + core prims

** DONE Fix improper-list doall + print_str
:PROPERTIES:
:TASK_ID: task-3
:STATUS: completed
:END:

rt.ex: doall realizes [h|LazySeq] improper lists; print_str handles them (LazySeq.sample path). Add improper? helper.

** DONE Update core.bl reduce to respect reduced
:PROPERTIES:
:TASK_ID: task-4
:STATUS: completed
:END:

priv/core.bl: make self-hosted reduce short-circuit on reduced?/deref; update interpose stale comment

* verify

** DONE Write wave25_transducer_test.exs
:PROPERTIES:
:TASK_ID: task-5
:STATUS: completed
:END:

Test reduced short-circuit, cpp shim via vendored slices, volatile r/w/swap, transducer 1-arities, interleave/interpose infinite+take

** DOING Compile + run all gates + re-measure jank slices
:PROPERTIES:
:TASK_ID: task-6
:STATUS: in_progress
:DEPENDS: task-1 task-2 task-3 task-4 task-5
:END:

mix compile --warnings-as-errors, wave25 + wave14/15 tests, beam_lisp.test, jank slice status
