#+TITLE: Session 154d8c75761fb2fd Todos
#+DATE: 2026-08-06
#+TODO: ITEM DOING BLOCKED | DONE

* impl

** DONE Create refs.ex (structs + Refs module)
:PROPERTIES:
:TASK_ID: task-1
:STATUS: completed
:END:

New file lib/beam_lisp/refs.ex: %BeamLisp.Atom{pid}, %BeamLisp.Promise{pid}, %BeamLisp.Future{task}, module BeamLisp.Refs with atom/deref(1,3)/swap!(2,3)/reset!/compare_and_set!/future_exec/future?/future_cancel/promise/deliver + promise_loop. Accept: compiles

** DONE Add @ reader sugar
:PROPERTIES:
:TASK_ID: task-2
:STATUS: completed
:DEPENDS: task-1
:END:

lib/beam_lisp/reader.ex: add [?@ | rest] -> deref_form(rest) in form/1, deref_form helper mirroring quote_form; update moduledoc. Accept: read_all("@x") == ({:list,[{:symbol,"deref"},{:symbol,"x"}]})

** DONE Seed refs prims + future macro + links in rt.ex
:PROPERTIES:
:TASK_ID: task-3
:STATUS: completed
:DEPENDS: task-1 task-2
:END:

lib/beam_lisp/rt.ex seed_core: merge refs_prims, intern future macro; seed_links: ref_links loop. Accept: mix compile --warnings-as-errors clean

* verify

** DONE Write examples/atoms.bl + verify run
:PROPERTIES:
:TASK_ID: task-5
:STATUS: completed
:DEPENDS: task-3
:END:

New examples/atoms.bl: counter atom incremented from 10 spawned processes (wait via receive), one future, one promise exchange. Deterministic, exit 0. Accept: mix beam_lisp.run examples/atoms.bl twice, identical output
